### ISSUE TITLE
multiple concurrent executions of bosh errands

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/cf-ops-automation#196]
### Expected behavior
Same errand do not run until previous finished. They must be serialized
### Observed behavior
    Errands enabled in ci-deployment overview are currently scheduled in concurrence.
    As a side effect this breaks smoke test executions, such as CFCR

### Affected release
3

**Comment by JCL38-ORANGE** [comment]
Hello,

The release shield v8 brings an import job in order to load backup configurations :  
https://github.com/starkandwayne/shield-boshrelease/tree/master/jobs/import
This job brings an auto-generation token mechanism in order to authenticate to shield daemon.
This mechanism doesn't support multiple concurrent executions.
It only supports serialized executions (because of the token name). 

Thanks a lot,
Jean-Christophe.

**Comment by o-orand** [comment]
This is released in COA [3.2.2](cf-ops-automation/releases/3.2.2)
see 6df8a073294fb3e86f1dd10fcc43c9d5146b9c22 and e0670f6
