### ISSUE TITLE
control-plane/save-deployed-pipelines: excessive job triggering 

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/cf-ops-automation#206]
### Expected behavior
Control plan should be triggered only on pipeline updates

### Observed behavior

[control-plane/save-deployed-pipelines](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/cda91fb016b0150b07f26124b2d5b3e4cb982774/concourse/pipelines/control-plane.yml#L85-L148) job is triggered on each resource check

### Affected release
Reproduced on version 3.2 (ie next version)

### Traces and logs
Related concourse issues: 
- inconsistent resources order returned by get-pipeline command: https://github.com/concourse/fly/issues/241
- check returns a different version even if pipeline config didn't change: https://github.com/concourse/concourse-pipeline-resource/issues/38

**Comment by lucaspinto** [comment]
After having looked at the concourse resource checked by the `save-deployed-pipelines`, it seems to me that the jobs starts over and over because the job itself is generating a change.

<img width="603" alt="screenshot 2019-01-04 at 10 40 52" src="https://user-images.githubusercontent.com/157468/50681878-41702a80-100d-11e9-8a87-45249883128d.png">

**Comment by lucaspinto** [comment]
Given this information, the two first, and not ideal, solutions I see are:
- make `fe-int-micro` a non-triggering resource
- move `control-plane` to another, possibly new, team.

**Comment by o-orand** [comment]
Upsteam bug are fixed in concourse 5. 
Closing as we are now in concourse-5
