### ISSUE TITLE
offer a preview in logs of interpolated (manifest + operators + vars)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cf-ops-automation#52]
To ease complex deployment troubleshooting, it would be useful to offer a preview of the combination of the files provided in manifest (including operators order).

**Comment by o-orand** [comment]
@poblin-orange : Do you think, using the [bosh-deployment-resource](https://github.com/cloudfoundry/bosh-deployment-resource) dry_run option is enough ? Otherwise we may consider openning an issue to add this kind of preview in [bosh-deployment-resource](https://github.com/cloudfoundry/bosh-deployment-resource).

`dry_run: Optional Shows the deployment diff without running a deploy. Defaults to false.`

**Comment by poblin-orange** [comment]
@o-orand if you mean 2 steps, dry-run then apply, that would be ok, if the interpolated result is dumped to the concourse logs.

**Comment by o-orand** [comment]
Study the dry run option should include `no_redact`

**Comment by o-orand** [comment]
closed by PR #142
